config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root 'application#home'

  resources :users
  resources :tasks
  resources :certificates
end

app/models/certificate.rb
require 'certificate_authority'

class Certificate
  include Mongoid::Document
  include Mongoid::Timestamps

  before_save :init
  belongs_to :user

  validates_format_of :domain, with: /(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w \.-]*)*\/?/

  field :cert, type: String
  field :parent, type: String
  
  field :root, type: Boolean, default: false
  field :organization, type: String
  field :text, type: String
  field :domain, type: String
  


  private

  def init
    if root
      
      
      
    end
  end
  
end

app/models/task.rb
class Task
  include Mongoid::Document
  include Mongoid::Timestamps

  before_save :nonlinearity
  
  mount_uploader :sbox, SboxUploader

  field :name, type: String
  field :body, type: String
  field :function, type: Array
  field :function_basic, type: Array
  field :function_linear, type: Array
  field :nonlinearity_value, type: Array
  field :SAC_value, type: Array
  
  private

  def nonlinearity
    self.body=""
    bytes_array=Array.new

    funkcje=Array.new(8) {|e| e=Array.new}
    funkcje_podstawowe=Array.new(8) {|e| e=Array.new}
    funkcje_liniowe=Array.new
    nieliniowosc=Array.new(8) {|e| e=1000}
    sac_tablica=Array.new(8)
    text=IO.binread(self.sbox.current_path)

    text.bytes.each { |e| bytes_array.push(e)  }
    bytes_array.reject!.each_with_index { |str, i| i.odd? }



    bytes_array.each { 
        |e|
        e.size.times do |counter|
          funkcje[counter].push(e[counter])
        end 
      }

    8.times do |i|
      v=1
      count=0
      256.times do |counter|
        funkcje_podstawowe[i][counter]=v
        count+=1
        (v==0 ? v=1 : v=0 and count=0) if count >= 2**(i)
      end
      
    end

    8.times do |i|
      j=i+1
      combinations=funkcje_podstawowe.combination(j).to_a
      wynik=Array.new(256) { |f| f=0  }
      
      combinations.each { |e| e.each{|f| wynik=xor(wynik,f)} and funkcje_liniowe.push(wynik) }
    end

    8.times do |i|
      funkcje_liniowe.size.times do |counter| 
        nl=xor_difference(funkcje_liniowe[counter],funkcje[i])
        nieliniowosc[i]=nl if nl<nieliniowosc[i]
      end
    end

    funkcje.size.times do |i|
      sac_tablica[i]=SAC(funkcje[i])
    end

    self.function=funkcje
    self.function_basic=funkcje_podstawowe
    self.function_linear=funkcje_liniowe
    self.nonlinearity_value=nieliniowosc
    self.SAC_value=sac_tablica
    funkcje.each { |e| e.each { |f| self.body+=to_bool(f).to_s  } and self.body+="\n"  }  
  end

  def to_bool num
    return true if num == 1
    return false if num == 0
  end

  def xor (f1,f2)
    if f1.size == f2.size
      wynik=Array.new(f1.size) { |i| i=0 }

      f1.size.times do |i|
        f1[i]==f2[i] ? wynik[i]=0 : wynik[i]=1
      end
      return wynik
    else
    return nil
    end
  end

  def xor_difference (f1,f2)
    count=0
    if f1.size == f2.size
      f1.size.times do |i|
        count+=1 unless f1[i]==f2[i]
      end
      return count
    else
    return 0
    end
  end

  def SAC (fnc)
    sac_vl=0
    arg_count=Math.log(fnc.size, 2)
    arg_count.to_i.times do |mask|
      tmp=0
      masked_function=Array.new(fnc.size)    
      fnc.size.times do |i|
        masked_function[i^(2**mask)]=fnc[i]
      end
      fnc.size.times do |i|
        tmp+=1 unless fnc[i]==masked_function[i]
      end
      sac_vl+=tmp
    end
    Rails.logger.debug "Show this message!"+sac_vl.to_s
    return sac_vl/(arg_count)/fnc.size
  end

end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  
  has_many :certificates

  field :admin, type: Boolean, default: false

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
  
  def to_key
    key = respond_to?(:id) && id.to_s
    key ? [key] : nil
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  expose(:recent_tasks) {Task.all.to_a.last(5)}
  expose(:recent_certs) {Certificate.all.to_a.last(5)}

  protect_from_forgery with: :exception

  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end

  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def home
  end


  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :first_name
      devise_parameter_sanitizer.for(:sign_up) << :last_name
      devise_parameter_sanitizer.for(:account_update) << :first_name
      devise_parameter_sanitizer.for(:account_update) << :last_name
    end
  
end

app/controllers/certificates_controller.rb
class CertificatesController < ApplicationController
expose(:certificate,  attributes: :certificate_params)
expose(:ca){Certificate.all.where(root: true)}

def new
end

def create
  if certificate.save
    if certificate.root
      redirect_to certificate_path(certificate)
    else
      send_data download_cert, :filename => "#{certificate.id}.pem"
    end
  else
    render :new
  end
end

def show
end

private

def download_cert
      r = CertificateAuthority::Certificate.new
      r.subject.common_name=  certificate.parent
      r.serial_number.number=1
      r.key_material.generate_key
      r.signing_entity = true
      signing_profile =
      {
        "extensions" =>
          {
          "basicConstraints" => {"ca" => true},"keyUsage" => {"usage" => ["critical", "keyCertSign"] }
          }
      }
      r.sign!(signing_profile)

  signing_profile = {
       "extensions" => {
          "basicConstraints" => {"ca" => false},
          "certificatePolicies" => {
          "user_notice" => {
            "explicit_text" => certificate.text+'2',
            "organization" => certificate.organization
          }
        }
       }
    }

      plain_cert = CertificateAuthority::Certificate.new
      plain_cert.subject.common_name= certificate.domain
      plain_cert.serial_number.number=4
      plain_cert.key_material.generate_key
      plain_cert.parent = r # or intermediate
      plain_cert.sign!(signing_profile)

      return plain_cert.to_pem
end

def certificate_params
  params.require(:certificate).permit(:cert,  :domain,  :root,  :parent, :organization, :text)
end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  expose(:task, attributes: :task_params)
  

  def new
  end

  def create
    if task.save
        redirect_to task_path(task)
    else
        render :new
    end
  end

  def show
  end

  private

  def task_params
    params.require(:task).permit(:name, :sbox)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  expose(:user)
  expose(:users)

  def index

  end

  def show
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_footer.haml
.navbar.navbar-default.navbar-fixed-bottom.h5
  .row.well-sm
    .col-xs-6.text-left Copyright Damian Romanów
    .col-xs-6.text-right Powered by Tweeter Bootstrap

app/views/application/_header.haml
.navbar.navbar-default.navbar-static-top{role: "navigation"}
  .container
    .navbar-header
      = link_to 'Crypto', root_path, class: 'navbar-brand'
    .p
      .navbar-collapse.collapse
        %ul.nav.navbar-nav.navbar-right
          - if false and current_user.try(:admin?)
            %li
              = link_to 'Admin', rails_admin.dashboard_path
          / %li
          /   = link_to 'Tasks', root_path
          - if false and user_signed_in?
            %li.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
                Account
                %b.caret
              %ul.dropdown-menu
                %li
                  = link_to 'My profile', user_path(current_user)
                %li
                  = link_to 'Edit account', edit_user_registration_path
                %li
                  = link_to 'Log out', destroy_user_session_path, method: 'delete'
          - else
            %li
              = link_to 'Log in', new_user_session_path

app/views/application/_task_list.haml
.col-md-12
  %ul#my-tab.nav.nav-tabs{"data-tabs" => "tabs"}
    %li.active
      %a{"data-toggle" => "tab", href: "#sbox"} Sbox proccesing
    %li
      %a{"data-toggle" => "tab", href: "#cert"} Certificates generation
  #my-tab.tab-content
    #sbox.tab-pane.active 
      %table.table
        %thead
          %tr.well
            %th.col-sm-4 Sbox
            %th.col-sm-4 Date
            %th.col-sm-4
              = link_to 'New',  new_task_path, class: 'btn btn-default'
        %tbody
          - recent_tasks.reverse.each { |t|
          %tr
            %td 
              = link_to t.sbox, task_path(t)
            %td
              = t.created_at
              - }
            %td
    #cert.tab-pane 
      %table.table
        %thead
          %tr.well
            %th.col-sm-4 Certificate
            %th.col-sm-4 Date
            %th.col-sm-4
              = link_to 'New',  new_certificate_path, class: 'btn btn-default'
        %tbody
          - recent_certs.reverse.each { |t|
          %tr
            %td 
              = link_to t.domain, certificate_path(t)
            %td
              = t.created_at
              - }
            %td 

  

app/views/application/home.html.haml
.row
  .col-md-8
    .h3 Hello cryptographer
    .p Site for hosting my tasks for Cryptography laboratory
  .col-md-4
    = render 'task_list'

app/views/certificates/_form.html.haml
.row
  = simple_form_for certificate, :defaults => { :wrapper_html => {:class => 'form-horizontal'} } do |f|
    = f.input :domain, label: 'Enter domain name'
    = f.input :organization, label: 'Enter organization name'
    = f.input :text, label: 'Additional comment'
    = f.input :root, as: :Boolean, label: 'Root certificate?'
    = f.input :parent, collection: ca,:label_method => :domain ,:value_method => :domain, :include_blank => true
    = f.button :submit, 'Generate certificate' 

app/views/certificates/new.html.haml
= render 'form'

app/views/certificates/show.html.haml
=render 'certificate'

app/views/layouts/_footer.haml
.row
  .col-sm-4.small Copyright Damian Romanów
  .col-md-4.col-md-offset-4.small Powered by Tweeter Bootstrap

app/views/layouts/_footer.html.haml
.row
  .col-sm-4.small Copyright Damian Romanów
  .col-md-4.col-md-offset-4.small Powered by Tweeter Bootstrap

app/views/layouts/_header.html.haml
.navbar-inverse
  gwegwe

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Crypto
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    =render 'header'
    .container
      = yield
    =render 'footer'

app/views/tasks/_form.haml
.row
  = simple_form_for task, :defaults => { :wrapper_html => {:class => 'form-horizontal'} } do |f|
    = f.input :sbox, as: :file, label: 'Choose sbox file from hard disc'
    = f.input :name, collection: ["Nonlinearity","SAC"], :include_blank => false
    = f.button :submit, 'Process sbox' 

app/views/tasks/_task.haml
%small 
  = task.name 
  %br 
    = task.sbox 
  %br
.container
  %ul#my-tab.nav.nav-tabs{"data-tabs" => "tabs"}
    %li.active
      %a{"data-toggle" => "tab", href: "#sboxfunctions"} Sbox functions
    %li
      %a{"data-toggle" => "tab", href: "#basicfunctions"} Basic functions
    %li
      %a{"data-toggle" => "tab", href: "#linearfunctions"} Linear functions
    %li
      %a{"data-toggle" => "tab", href: "#nonlinearity"} Nonlinearity
    %li
      %a{"data-toggle" => "tab", href: "#SAC"} SAC
  #my-tab.tab-content
    #sboxfunctions.tab-pane.active 
      %table.table{:style => "word-wrap: break-word; table-layout: fixed;"}
        %thead
          %tr
            %th Number
            %th Body
        %tbody
          - task.function.size.times do |i|
            %tr
              %td 
                = i +1
              %td
                - fbody=''
                - task.function[i].size.times do |j|
                  - fbody+=task.function[i][j].to_s
                = fbody
    #basicfunctions.tab-pane 
      %table.table{:style => "word-wrap: break-word; table-layout: fixed;"}
        %thead
          %tr
            %th Number
            %th Body
        %tbody
          - task.function_basic.size.times do |i|
            %tr
              %td 
                = i + 1
              %td
                - fbody=''
                - task.function_basic[i].size.times do |j|
                  - fbody+=task.function_basic[i][j].to_s
                = fbody
    #linearfunctions.tab-pane 
      %table.table{:style => "word-wrap: break-word; table-layout: fixed;"}
        %thead
          %tr
            %th Number
            %th Body
        %tbody
          - task.function_linear.size.times do |i|
            %tr
              %td 
                = i+1
              %td
                - fbody=''
                - task.function_linear[i].size.times do |j|
                  - fbody+=task.function_linear[i][j].to_s
                = fbody
    #nonlinearity.tab-pane
      %table.table
        %thead
          %tr
            %th Number
            %th Nonlinearity
        %tbody
          - task.nonlinearity_value.size.times do |i|
            %tr
              %td 
                = i + 1 
              %td
                = task.nonlinearity_value[i]
    #SAC.tab-pane
      %table.table
        %thead
          %tr
            %th Number
            %th SAC
        %tbody
          - task.SAC_value.size.times do |i|
            %tr
              %td 
                = i + 1
              %td
                = task.SAC_value[i]

app/views/tasks/file_input.haml
= simple_form_for :file do |f|
  = f.file_field :file
  = f.button :submit

app/views/tasks/new.haml
= render 'form'

app/views/tasks/nonlinearity.haml
.form-group
  %label{for: "exampleInputFile"} Choose sbox file:
  %input#exampleInputFile{type: "file"}/
  %p.help-block Example block-level help text here.

app/views/tasks/show.haml
= render 'task'